version: '3.8'

services:
  event-api:
    build: .
    image: rails-docker
    restart: "no"
    environment:
      - DBHOST=postgresql
      - DBUSER=postgres
      - DBPASSWORD=password
    ports:
      - '3000:3000'
    env_file:
      - .env
    links:
      - postgresql
      - redis
        #depends_on:
        #  - postgresql

  postgresql:
    image: postgres
    ports:
       - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - event-api-postgres:/var/lib/postgresql/data/

  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - event-api-redis:/var/lib/redis/data

  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    links:
      - postgresql
      - redis
    env_file:
      - .env
volumes:
  event-api-postgres:
  event-api-redis:
