version: '3.8'

services:
  api:
    depends_on:
      - postgres
      - redis
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - .env
        #     environment:
        #       - DBHOST=postgresql
        #       - DBUSER=postgres
        #       - DBPASSWORD=password

  postgres:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
       - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    env_file:
      - .env

  redis:
    image: redis
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - '6379:6379'
    command: redis-server

  sidekiq:
    depends_on:
      - postgres
      - redis
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/app'
    env_file:
      - .env

volumes:
  postgres:
  redis:
